In [12]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

frases = [
    "Hola mundo",
    "Hola a todos",
    "Hola a todo el mundo"
]

# Genera el diccionario de tokens
tokenizer = Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('word_index =', word_index)


word_index = {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6}


In [13]:

secuencias = [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2]]

In [14]:

#Rellena las secuencias a una longitud uniforme
relleno = keras.preprocessing.sequence.pad_sequences (secuencias) 
print('rellena =\n',relleno)

rellena =
 [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]]


In [19]:
import tensorflow as tf
print(tf.__version__)


2.17.0


In [22]:
pip install keras-preprocessing


   ---------------------------------------- 0.0/42.6 kB ? eta -:--:--
   ---------------------------------------- 0.0/42.6 kB ? eta -:--:--
   ------------------- -------------------- 20.5/42.6 kB ? eta -:--:--
   ---------------------------- ----------- 30.7/42.6 kB 325.1 kB/s eta 0:00:01
   ---------------------------------------- 42.6/42.6 kB 258.7 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

# Rest of your code


In [5]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen dia, como estas hoy'
]

# Genera el diccionario de tokens
tokenizer = Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('\nword_index =', word_index)

# Generación de secuencia tokenizadas
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)

# Rellena las secuencias a una longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('rellena =\n', relleno)



word_index = {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6, 'buen': 7, 'dia': 8, 'como': 9, 'estas': 10, 'hoy': 11}
secuencias = [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2], [7, 8, 9]]
rellena =
 [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]
 [0 0 7 8 9]]


In [10]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen dia, como estas hoy'
]
#Genera el diccionario de tokens
tokenizer = Tokenizer(num_words=10, oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('\nword_index =', word_index)
#Generacion de secuencia tokenizadas
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)
#Rellena las secuencias a una longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('rellena =\n', relleno)




word_index = {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'dia': 9, 'como': 10, 'estas': 11, 'hoy': 12}
secuencias = [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]
rellena =
 [[0 0 0 2 3]
 [0 0 2 4 5]
 [2 4 6 7 3]
 [8 9 1 1 1]]


In [14]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen dia, como estas hoy'
]
#Genera el diccionario de tokens
tokenizer = Tokenizer(num_words=10, oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('\nword_index =', word_index)
#Generacion de secuencia tokenizadas
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)
#Rellena las secuencias a una longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences (secuencias,
                                                      padding = 'post',
                                                       truncating = 'post', )


print('rellena =\n', relleno)




word_index = {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'dia': 9, 'como': 10, 'estas': 11, 'hoy': 12}
secuencias = [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]
rellena =
 [[2 3 0 0 0]
 [2 4 5 0 0]
 [2 4 6 7 3]
 [8 9 1 1 1]]
